Project/Project/Models/Login.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Project.Models
{
    public class Login 
    {
        public int id { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
    }
}

Project/Project/Models/Mother.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Project.Models
{
    class Mother
    {
        public int id { get; set; }
        public string Name { get; set; }

        public virtual List<Question> Questions { get; set; }
    }
}

Project/Project/Controllers/MotherShopsController.cs
using Project.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Project.Controllers
{
    public class MotherShopsController : Controller
    {
        Service service;
        // GET: MotherShops
        public ActionResult Index()
        {

            return View();
        }
    }
}

Project/Project/Controllers/MothersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Project.Controllers
{
    public class MothersController : Controller
    {
        // GET: Mothers
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Login()
        {
            return View();
        }
        public ActionResult Register()
        {
            return View();
        }
        public ActionResult Search()
        {
            return View();
        }
    }
}

Project/Project/Views/Mothers/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<header id="header" class="container-fluid" >
    <nav class="navbar navbar-default navbar-fixed-top" style="background-color:white">
        <div class="container">
            <div class="navbar-header" >
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="#"><img src="~/images/logo.png" /></a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li style="margin:7px 0px 0px 5px">@Html.ActionLink("Login", "Login", "Mothers")</li>
                    <li style="margin:7px 0px 0px 5px">@Html.ActionLink("Register", "Register", "Mothers")</li>
                    <li style="margin:20px 0px 0px 290px">@Html.TextBox("name")</li>
                    <li style="margin:20px 0px 0px 0px"><button id="searchbtn" value="search" style="background-image:url(~/images/logo.png)">Search</button></li>
                </ul>
            </div>
        </div>
    </nav>
    <nav class="navbar navbar-default" style="background-color:rosybrown;height:70px">
        <div>
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Mothers", "Index", "MotherShops")</li>
                    <li>@Html.ActionLink("Babies", "Register", "Mothers")</li>
                    <li>@Html.ActionLink("Doctors", "Search", "Mothers")</li>
                    <li>@Html.ActionLink("Shops", "Search", "Mothers")</li>
                    
                </ul>
        </div>
    </nav>
</header>
<div id="content">
    <div class="container">
        <div id="myCarousel" class="carousel slide" data-ride="carousel">
            <!-- Indicators -->
            <ol class="carousel-indicators">
                <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                <li data-target="#myCarousel" data-slide-to="1"></li>
                <li data-target="#myCarousel" data-slide-to="2"></li>
            </ol>

            <!-- Wrapper for slides -->
            <div class="carousel-inner">
                <div class="item active">
                    <img src="~/images/1.jpg" style="width:100%;">
                </div>

                <div class="item">
                    <img src="~/images/2.jpg" style="width:100%;">
                </div>

                <div class="item">
                    <img src="~/images/3.jpg" style="width:100%;">
                </div>
            </div>

            <!-- Left and right controls -->
            <a class="left carousel-control" href="#myCarousel" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="right carousel-control" href="#myCarousel" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
    </div>
</div>
<footer id="footer">

</footer>

Project/Project/Views/Mothers/Login.cshtml
@{
    ViewBag.Title = "Login";
}
<div>
    <h2>Login</h2>
    @using (Html.BeginForm())
    {
        @Html.Label("UserName");
        @Html.TextBox("");
        @Html.Label("Password");
        @Html.TextBox("");
        <input type="submit" value="Login" />
    }
</div>